# -*- coding: utf-8 -*-
"""Laboratorio_8_Carlos_Gil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQ75kgVxLsYE7XGPmZz6A0dOqdtnngp4
"""

# ============================================================
# LABORATORIO: MINERÍA DE DATOS APLICADA A CLIENTES RETAIL
# Empresa: Comercial Andina S.A.C.
# Herramienta: Google Colab - Python
# Alumno: Carlos Gil Carrillo
# Curso: ANALISIS ESTADISTICO Y DATA MINING (SRM)
# ============================================================

# ============================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Configuración visual básica
sns.set()

print("Librerías cargadas correctamente")

# ============================================================
# 2. CREACIÓN DE LA BASE DE DATOS EMPRESARIAL
# ============================================================

np.random.seed(42)

n_clientes = 150

datos = pd.DataFrame({
"cliente_id": range(1, n_clientes + 1),
"edad": np.random.randint(18, 70, n_clientes),
"ingreso_mensual": np.random.randint(1200, 12000, n_clientes),
"frecuencia_compra": np.random.randint(1, 25, n_clientes),
"gasto_promedio": np.random.randint(50, 900, n_clientes),
"canal_compra": np.random.choice(["Tienda", "Online", "Mixto"], n_clientes),
"satisfaccion": np.random.choice(["Bajo", "Medio", "Alto"], n_clientes),
"compra_alta": np.random.choice([0, 1], n_clientes, p=[0.55, 0.45])
})

print("Base de datos creada correctamente")

datos.head()

# ==========================================
# Estadísticas descriptivas del dataset
# ==========================================

# La base de datos contiene 150 clientes y no presenta valores faltantes
# después del proceso de limpieza.

# La edad de los clientes tiene un promedio de 42.7 años, con una mediana
# de 42 años y un rango entre 18 y 69 años. Esto indica una distribución
# relativamente equilibrada de clientes adultos.

# El ingreso mensual promedio es de 6,398.79 unidades monetarias, con una
# desviación estándar de 2,897.97. Los ingresos varían entre 1,298 y 11,629,
# mostrando una población con niveles económicos diversos.

# La frecuencia de compra tiene una media de 12.8 compras por período,
# una mediana de 14 y valores entre 1 y 24 compras. Esto sugiere que existen
# tanto clientes ocasionales como clientes recurrentes.

# El gasto promedio presenta una media de 491.94 unidades monetarias y una
# mediana de 499. Los valores oscilan entre 61 y 898, sin evidencia de
# valores extremos significativos tras la limpieza de datos.

# La variable objetivo "compra_alta" tiene una media de 0.447, lo que indica
# que aproximadamente el 44.7 % de los clientes pertenece a la categoría
# de compra alta, mientras que el 55.3 % restante corresponde a compra baja.

# En general, las estadísticas descriptivas muestran un conjunto de datos
# balanceado, con variabilidad suficiente en ingresos, frecuencia y gasto,
# lo que permite realizar análisis predictivos y segmentación de clientes.

datos.describe()

# ==========================================
# Estructura del dataset (datos.info())
# ==========================================

# La base de datos contiene 150 registros y 9 variables.
# Todas las columnas presentan 150 valores no nulos,
# por lo que no existen datos faltantes después del proceso de limpieza.

# Se identifican tres tipos de datos:
# - Variables enteras (int64): cliente_id, edad,
#   frecuencia_compra, compra_alta y satisfaccion_codificada.
# - Variables decimales (float64): ingreso_mensual y gasto_promedio.
# - Variables categóricas (object): canal_compra y satisfaccion.

# La variable cliente_id funciona como identificador único
# de cada cliente y no aporta valor predictivo directo.

# Las variables edad, ingreso_mensual, frecuencia_compra y gasto_promedio
# representan características cuantitativas del comportamiento del cliente.

# Las variables canal_compra y satisfaccion contienen información
# categórica relacionada con el canal utilizado y el nivel de satisfacción.

# La variable compra_alta corresponde a la variable objetivo utilizada
# en el modelo de clasificación, donde 1 representa clientes de compra alta
# y 0 clientes de compra baja.

# La variable satisfaccion_codificada es una transformación numérica
# de la variable categórica satisfaccion para facilitar su uso
# en algoritmos de aprendizaje automático.

# El consumo de memoria es de aproximadamente 10.7 KB,
# por lo que se trata de un conjunto de datos pequeño
# y fácil de procesar computacionalmente.

datos.info()

# ============================================================
# 3. SIMULACIÓN DE PROBLEMAS EN LOS DATOS
# ============================================================

# Se insertan algunos valores faltantes
datos.loc[5, "ingreso_mensual"] = np.nan
datos.loc[18, "gasto_promedio"] = np.nan
datos.loc[32, "canal_compra"] = np.nan
datos.loc[47, "satisfaccion"] = np.nan

# Se inserta un valor extremo para simular error de registro
datos.loc[10, "gasto_promedio"] = 15000

# Se inserta una edad inconsistente
datos.loc[20, "edad"] = -5

print("Se agregaron valores faltantes y errores para practicar limpieza")
datos.loc[[5, 10, 18, 20, 32, 47]]

# ============================================================
# 4. EXPLORACIÓN INICIAL DE LOS DATOS
# ============================================================

print("\nPrimeras filas del dataset:")
print(datos.head())

print("\nTamaño de la base de datos:")
print(datos.shape)

print("\nTipos de datos:")
print(datos.dtypes)

print("\nResumen estadístico:")
print(datos.describe())

print("\nValores faltantes por columna:")
datos.isnull().sum()

# ============================================================
# 5. LIMPIEZA DE DATOS
# ============================================================

# Corrección de edad negativa
# Regla de negocio: la edad debe estar entre 18 y 70 años.
# Si aparece una edad negativa, se reemplaza por la mediana de edades válidas.

mediana_edad = datos.loc[datos["edad"] >= 18, "edad"].median()
datos.loc[datos["edad"] < 18, "edad"] = mediana_edad

print("\nEdad negativa corregida")
print(datos.loc[20, "edad"])

# ============================================================
# 6. TRATAMIENTO DE DATOS FALTANTES
# ============================================================

# Imputación para variables numéricas con la mediana
datos["ingreso_mensual"] = datos["ingreso_mensual"].fillna(datos["ingreso_mensual"].median())
datos["gasto_promedio"] = datos["gasto_promedio"].fillna(datos["gasto_promedio"].median())

# Imputación para variables categóricas con la moda
datos["canal_compra"] = datos["canal_compra"].fillna(datos["canal_compra"].mode()[0])
datos["satisfaccion"] = datos["satisfaccion"].fillna(datos["satisfaccion"].mode()[0])

print("\nValores faltantes después de la imputación:")
print(datos.isnull().sum())

# ============================================================
# 7. DETECCIÓN Y TRATAMIENTO DE VALORES ATÍPICOS
# ============================================================

# Se analizó la variable gasto_promedio mediante un boxplot para identificar
# posibles valores atípicos que pudieran distorsionar los resultados
# estadísticos y los modelos posteriores.

# Para detectar outliers se utilizó el método del rango intercuartílico (IQR),
# que considera como atípicos aquellos valores que se encuentran por debajo
# de Q1 - 1.5 * IQR o por encima de Q3 + 1.5 * IQR.

# El procedimiento permitió identificar un valor extremo en la variable
# gasto_promedio que se encontraba fuera de los límites aceptables de la
# distribución de los datos.

# Debido a que este valor no representaba el comportamiento normal de los
# clientes y podía afectar la media, la desviación estándar y los modelos
# predictivos, se decidió corregirlo.

# En lugar de eliminar el registro, el valor atípico fue reemplazado por la
# mediana de los gastos válidos. La mediana es una medida robusta que no se
# ve afectada por valores extremos y permite conservar el registro dentro
# del conjunto de datos.

# Finalmente, se generó un segundo boxplot para verificar que la variable
# gasto_promedio ya no presentara valores atípicos significativos y que la
# distribución fuera más representativa del comportamiento real de los clientes.

# Se analiza la variable gasto_promedio porque contiene un valor extremo

plt.figure(figsize=(8, 4))
sns.boxplot(x=datos["gasto_promedio"])
plt.title("Boxplot de gasto promedio antes de tratar outliers")
plt.xlabel("Gasto promedio")
plt.show()

# Método IQR para detectar valores atípicos

Q1 = datos["gasto_promedio"].quantile(0.25)
Q3 = datos["gasto_promedio"].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("\nLímite inferior:", limite_inferior)
print("Límite superior:", limite_superior)

outliers = datos[(datos["gasto_promedio"] < limite_inferior) | (datos["gasto_promedio"] > limite_superior)]

print("\nValores atípicos detectados:")
print(outliers)

# Reemplazo del outlier por la mediana
mediana_gasto = datos.loc[datos["gasto_promedio"] <= limite_superior, "gasto_promedio"].median()
datos.loc[datos["gasto_promedio"] > limite_superior, "gasto_promedio"] = mediana_gasto

plt.figure(figsize=(8, 4))
sns.boxplot(x=datos["gasto_promedio"])
plt.title("Boxplot de gasto promedio después de tratar outliers")
plt.xlabel("Gasto promedio")
plt.show()

# ============================================================
# 8. TRANSFORMACIÓN DE VARIABLES CATEGÓRICAS
# ============================================================

# En esta etapa se convierten las variables categóricas en formatos numéricos
# para que puedan ser utilizadas por los algoritmos de machine learning.

# ------------------------------------------------------------
# 1. Codificación ordinal de la variable satisfacción
# ------------------------------------------------------------

# La variable "satisfaccion" tiene un orden natural:
# Bajo < Medio < Alto

# Se asignan valores numéricos respetando ese orden:
# Bajo = 1, Medio = 2, Alto = 3

mapa_satisfaccion = {
    "Bajo": 1,
    "Medio": 2,
    "Alto": 3
}

datos["satisfaccion_codificada"] = datos["satisfaccion"].map(mapa_satisfaccion)

# Esta transformación permite representar una variable cualitativa ordinal
# como una variable numérica manteniendo su jerarquía.

# ------------------------------------------------------------
# 2. One-hot encoding para canal de compra
# ------------------------------------------------------------

# La variable "canal_compra" es categórica nominal (no tiene orden),
# por lo que no se puede asignar un valor numérico directo sin introducir sesgo.

# Se aplica One-Hot Encoding para crear columnas binarias:
# - canal_compra_Online
# - canal_compra_Tienda
# - canal_compra_Mixto

datos_transformados = pd.get_dummies(
    datos,
    columns=["canal_compra"],
    drop_first=False
)

# Cada nueva columna toma el valor:
# 1 (True) si el cliente pertenece a ese canal
# 0 (False) si no pertenece

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# El dataset resultante contiene ahora variables numéricas y binarias,
# lo que permite su uso directo en modelos de machine learning
# como árboles de decisión, regresión logística o clustering.

# La transformación conserva la información original:
# - satisfacción mantiene su orden lógico
# - canal de compra se representa sin imponer jerarquías artificiales

# Esto mejora la calidad del modelado y evita interpretaciones incorrectas
# por parte de los algoritmos.

# ============================================================
# 9. SELECCIÓN DE VARIABLES PARA EL MODELO
# ============================================================

# En esta etapa se definen las variables que serán utilizadas
# para entrenar el modelo de machine learning.

# ------------------------------------------------------------
# Variables predictoras (X)
# ------------------------------------------------------------

# Se seleccionan variables que representan el comportamiento del cliente:
# - edad: información demográfica
# - ingreso_mensual: capacidad económica
# - frecuencia_compra: hábito de consumo
# - gasto_promedio: nivel de consumo
# - satisfaccion_codificada: nivel de satisfacción del cliente
# - canal_compra_*: canal utilizado para realizar compras

variables_modelo = [
    "edad",
    "ingreso_mensual",
    "frecuencia_compra",
    "gasto_promedio",
    "satisfaccion_codificada",
    "canal_compra_Mixto",
    "canal_compra_Online",
    "canal_compra_Tienda"
]

# Matriz de características (features)
X = datos_transformados[variables_modelo]

# ------------------------------------------------------------
# Variable objetivo (y)
# ------------------------------------------------------------

# La variable "compra_alta" indica si el cliente pertenece a la categoría
# de alta compra (1) o no (0), y es la variable que el modelo debe predecir.

y = datos_transformados["compra_alta"]

# ------------------------------------------------------------
# Justificación de la selección
# ------------------------------------------------------------

# Las variables seleccionadas combinan información demográfica,
# económica, conductual y de experiencia del cliente.

# Esto permite al modelo aprender patrones más completos sobre
# qué factores influyen en una compra alta.

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# X contiene las variables predictoras utilizadas para el entrenamiento.
# y contiene la variable objetivo que el modelo intentará predecir.

# Esta separación es fundamental para cualquier proceso de aprendizaje supervisado.

print("\nVariables predictoras:")

print(X.head())

print("\nVariable objetivo:")

print(y.head())

# ============================================================
# 10. NORMALIZACIÓN DE VARIABLES
# ============================================================

# En esta etapa se realiza la estandarización de las variables predictoras
# para que todas tengan la misma escala numérica.

# ------------------------------------------------------------
# ¿Por qué es necesario?
# ------------------------------------------------------------

# Las variables del dataset tienen unidades y rangos diferentes:
# - edad: valores entre ~18 y 69
# - ingreso_mensual: miles de unidades
# - frecuencia_compra: valores pequeños
# - gasto_promedio: valores intermedios

# Si no se normalizan, las variables con valores más grandes
# pueden dominar el modelo y sesgar los resultados.

# ------------------------------------------------------------
# Método utilizado: StandardScaler
# ------------------------------------------------------------

# StandardScaler aplica la estandarización Z-score:
# cada valor se transforma restando la media y dividiendo por la desviación estándar.

# Esto produce variables con:
# - media ≈ 0
# - desviación estándar ≈ 1

escalador = StandardScaler()
X_escalado = escalador.fit_transform(X)

# Se convierte el resultado en DataFrame para mantener interpretabilidad
X_escalado = pd.DataFrame(X_escalado, columns=variables_modelo)

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# Los datos ahora están en una escala común, lo que permite que
# algoritmos como:
# - regresión logística
# - k-means
# - máquinas de soporte vectorial
# - redes neuronales

# funcionen correctamente sin que una variable tenga más peso
# solo por su magnitud numérica.

# Esto mejora la estabilidad del modelo y la calidad de las predicciones.

print("\nDatos normalizados:")
print(X_escalado.head())

# ============================================================
# 11. DIVISIÓN DE DATOS EN ENTRENAMIENTO Y PRUEBA
# ============================================================

# En esta etapa se separa el dataset en dos subconjuntos:
# uno para entrenar el modelo y otro para evaluarlo.

# ------------------------------------------------------------
# ¿Por qué es necesario?
# ------------------------------------------------------------

# Si se entrenara y evaluara el modelo con los mismos datos,
# no se podría medir su capacidad real de generalización.
# El modelo podría simplemente "memorizar" los datos (overfitting).

# ------------------------------------------------------------
# División realizada
# ------------------------------------------------------------

# - Conjunto de entrenamiento (train): 75% de los datos
#   Se utiliza para ajustar los parámetros del modelo.

# - Conjunto de prueba (test): 25% de los datos
#   Se utiliza para evaluar el desempeño del modelo en datos no vistos.

# ------------------------------------------------------------
# Parámetros utilizados
# ------------------------------------------------------------

# test_size=0.25
# → define que el 25% de los datos se reservan para prueba.

# random_state=42
# → asegura reproducibilidad del experimento (mismo split siempre).

# stratify=y
# → mantiene la misma proporción de clases (0 y 1) en train y test,
# evitando desbalance entre conjuntos.

X_train, X_test, y_train, y_test = train_test_split(
    X_escalado,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# Se obtienen dos conjuntos:
# - X_train / y_train → usados para entrenar el modelo
# - X_test / y_test → usados para evaluar su rendimiento

# Esto permite una evaluación más realista y confiable
# del comportamiento del modelo en datos nuevos.

print("\nTamaño del conjunto de entrenamiento:")
print(X_train.shape)

print("\nTamaño del conjunto de prueba:")
print(X_test.shape)

# ============================================================
# 12. MODELO DE CLASIFICACIÓN: ÁRBOL DE DECISIÓN
# ============================================================

# En esta etapa se entrena un modelo de clasificación supervisada
# utilizando un Árbol de Decisión.

# ------------------------------------------------------------
# ¿Qué es un árbol de decisión?
# ------------------------------------------------------------

# Es un algoritmo que divide los datos en ramas según reglas
# basadas en las variables predictoras.
# Cada división busca reducir la impureza y mejorar la separación
# entre clases (en este caso, compra alta vs no compra alta).

# ------------------------------------------------------------
# Configuración del modelo
# ------------------------------------------------------------

modelo_arbol = DecisionTreeClassifier(
    max_depth=4,      # limita la profundidad del árbol para evitar overfitting
    random_state=42   # asegura resultados reproducibles
)

# ------------------------------------------------------------
# Entrenamiento del modelo
# ------------------------------------------------------------

# El modelo aprende patrones a partir del conjunto de entrenamiento
modelo_arbol.fit(X_train, y_train)

# ------------------------------------------------------------
# Predicción
# ------------------------------------------------------------

# Se generan predicciones usando el conjunto de prueba
predicciones = modelo_arbol.predict(X_test)

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# El modelo ha sido entrenado correctamente y ya puede ser utilizado
# para predecir si un cliente pertenece a la categoría de compra alta
# en función de sus características.

# La limitación de profundidad (max_depth=4) ayuda a mantener el modelo
# interpretable y reduce el riesgo de sobreajuste.


print("\nModelo de árbol de decisión entrenado correctamente")

# ============================================================
# 13. EVALUACIÓN DEL MODELO DE CLASIFICACIÓN
# ============================================================

# En esta etapa se evalúa el desempeño del árbol de decisión
# utilizando diferentes métricas de clasificación.

# ------------------------------------------------------------
# Métricas utilizadas
# ------------------------------------------------------------

# Accuracy:
# Mide el porcentaje total de predicciones correctas
# (tanto clase 0 como clase 1).

# Precision:
# De todos los clientes predichos como "compra alta (1)",
# qué proporción realmente lo era.
# Es importante cuando queremos evitar falsos positivos.

# Recall:
# De todos los clientes que realmente eran "compra alta (1)",
# qué proporción fue correctamente identificada.
# Es importante cuando queremos evitar perder clientes valiosos.

# ------------------------------------------------------------
# Cálculo de métricas
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, predicciones)
precision = precision_score(y_test, predicciones)
recall = recall_score(y_test, predicciones)

print("\nRESULTADOS DEL MODELO DE CLASIFICACIÓN")
print("Accuracy:", round(accuracy, 3))
print("Precision:", round(precision, 3))
print("Recall:", round(recall, 3))
print("\n")


# ------------------------------------------------------------
# RESULTADOS OBTENIDOS
# ------------------------------------------------------------

# Accuracy: 0.500
# → El modelo acierta el 50% de los casos, lo cual indica
#   un rendimiento bajo (similar a una predicción aleatoria).

# Precision: 0.455
# → Solo el 45.5% de los clientes predichos como compra alta
#   realmente pertenecen a esa categoría.

# Recall: 0.588
# → El modelo logra identificar el 58.8% de los clientes
#   que realmente son de compra alta.

# ------------------------------------------------------------
# Reporte de clasificación
# ------------------------------------------------------------

# Clase 0 (no compra alta):
# - Precision: 0.56
# - Recall: 0.43
# → El modelo identifica mejor esta clase en precisión,
#   pero pierde varios casos reales (bajo recall).

# Clase 1 (compra alta):
# - Precision: 0.45
# - Recall: 0.59
# → Detecta más clientes de compra alta, pero con más errores.

# ------------------------------------------------------------
# MATRIZ DE CONFUSIÓN
# ------------------------------------------------------------

matriz = confusion_matrix(y_test, predicciones)

# La matriz permite visualizar:
# - Verdaderos positivos
# - Verdaderos negativos
# - Falsos positivos
# - Falsos negativos

# Se representa con un heatmap para facilitar su interpretación.

plt.figure(figsize=(6, 4))
sns.heatmap(matriz, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de confusión")
plt.xlabel("Predicción del modelo")
plt.ylabel("Valor real")
plt.show()

# ------------------------------------------------------------
# CONCLUSIÓN
# ------------------------------------------------------------

# El modelo presenta un desempeño limitado, con accuracy del 50%.
# Esto indica que aún no es suficientemente robusto para producción
# y requiere mejoras en variables, balanceo o ajuste de hiperparámetros.


print("\nReporte de clasificación:")
print(classification_report(y_test, predicciones))

# ============================================================
# 14. VISUALIZACIÓN DEL ÁRBOL DE DECISIÓN
# ============================================================

# En esta etapa se genera una representación gráfica del modelo
# de árbol de decisión ya entrenado.

# ------------------------------------------------------------
# ¿Para qué sirve esta visualización?
# ------------------------------------------------------------

# El diagrama del árbol permite interpretar cómo el modelo
# toma decisiones paso a paso.

# Cada nodo representa una condición sobre una variable
# (por ejemplo: gasto_promedio <= cierto valor),
# y cada rama representa el resultado de esa decisión.

# ------------------------------------------------------------
# Elementos del gráfico
# ------------------------------------------------------------

# - feature_names:
#   Muestra los nombres de las variables utilizadas en cada división.

# - class_names:
#   Indica las clases objetivo:
#   "Compra baja" y "Compra alta".

# - filled=True:
#   Colorea los nodos según la clase dominante,
#   facilitando la interpretación visual.

# - rounded=True:
#   Mejora la estética del árbol con nodos redondeados.

# ------------------------------------------------------------
# INTERPRETACIÓN
# ------------------------------------------------------------

# El árbol permite identificar:
# - Qué variables tienen mayor impacto en la decisión.
# - En qué orden el modelo segmenta a los clientes.
# - Qué reglas utiliza para clasificar "compra alta".

# Esto hace que el modelo sea interpretable,
# a diferencia de algoritmos más complejos como redes neuronales.

plt.figure(figsize=(18, 8))

plot_tree(
    modelo_arbol,
    feature_names=variables_modelo,
    class_names=["Compra baja", "Compra alta"],
    filled=True,
    rounded=True
)

plt.title("Árbol de decisión para clasificar clientes")
plt.show()

# ============================================================
# 15. IMPORTANCIA DE VARIABLES
# ============================================================

# En esta etapa se analiza qué variables tienen mayor influencia
# en las decisiones del modelo de árbol de decisión.

# ------------------------------------------------------------
# ¿Qué es la importancia de variables?
# ------------------------------------------------------------

# Es una métrica interna del modelo que indica cuánto contribuye
# cada variable a reducir la impureza en el árbol.

# En otras palabras:
# - Variables con mayor importancia influyen más en la predicción.
# - Variables con menor importancia aportan menos información útil.

# ------------------------------------------------------------
# Cálculo de importancias
# ------------------------------------------------------------

importancias = pd.DataFrame({
    "Variable": variables_modelo,
    "Importancia": modelo_arbol.feature_importances_
}).sort_values(by="Importancia", ascending=False)

# ------------------------------------------------------------
# RESULTADO TABULAR
# ------------------------------------------------------------

# Se ordenan las variables de mayor a menor importancia
# para identificar los factores más relevantes en la predicción
# de "compra alta".

print("\nImportancia de variables en el modelo:")
print(importancias)

# ------------------------------------------------------------
# VISUALIZACIÓN
# ------------------------------------------------------------

# Se genera un gráfico de barras para visualizar claramente
# la contribución de cada variable al modelo.

plt.figure(figsize=(10, 5))

sns.barplot(
    data=importancias,
    x="Importancia",
    y="Variable"
)

plt.title("Importancia de variables en la clasificación")
plt.xlabel("Importancia")
plt.ylabel("Variable")
plt.show()

# ------------------------------------------------------------
# INTERPRETACIÓN
# ------------------------------------------------------------

# Este análisis permite identificar qué factores explican mejor
# la variable objetivo "compra_alta".

# En general, variables como gasto_promedio o ingreso_mensual
# suelen tener mayor peso, ya que están directamente relacionadas
# con el comportamiento de compra del cliente.

# Esto ayuda a:
# - Entender el modelo
# - Validar lógica de negocio
# - Tomar decisiones estratégicas de marketing

# ============================================================
# 16. CLUSTERING: SEGMENTACIÓN DE CLIENTES CON K-MEANS
# ============================================================

# En esta etapa se realiza una segmentación no supervisada
# de los clientes utilizando el algoritmo K-Means.

# ------------------------------------------------------------
# ¿Qué es K-Means?
# ------------------------------------------------------------

# K-Means es un algoritmo de clustering que agrupa observaciones
# en K grupos (clusters) según su similitud.

# Los clientes dentro de un mismo cluster comparten características
# similares en términos de comportamiento o valor.

# ------------------------------------------------------------
# Selección de variables
# ------------------------------------------------------------

# Se eligen variables relacionadas con el valor comercial del cliente:
# - ingreso_mensual: capacidad económica
# - frecuencia_compra: comportamiento de compra
# - gasto_promedio: nivel de consumo
# - satisfaccion_codificada: percepción del cliente

variables_cluster = [
    "ingreso_mensual",
    "frecuencia_compra",
    "gasto_promedio",
    "satisfaccion_codificada"
]

X_cluster = datos_transformados[variables_cluster]

# ------------------------------------------------------------
# Normalización de variables
# ------------------------------------------------------------

# Se aplica StandardScaler para asegurar que todas las variables
# tengan la misma escala y ninguna domine el cálculo de distancias.

escalador_cluster = StandardScaler()
X_cluster_escalado = escalador_cluster.fit_transform(X_cluster)

# ------------------------------------------------------------
# Entrenamiento del modelo K-Means
# ------------------------------------------------------------

# Se define el número de clusters (k=3), representando:
# - Clientes de bajo valor
# - Clientes de valor medio
# - Clientes de alto valor

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

# Se ajusta el modelo y se asigna cada cliente a un cluster
datos_transformados["cluster"] = kmeans.fit_predict(X_cluster_escalado)

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

# Cada cliente queda asignado a un grupo (0, 1 o 2),
# lo que permite realizar segmentación de mercado.

# Esta segmentación puede utilizarse para:
# - Personalización de campañas de marketing
# - Estrategias de fidelización
# - Identificación de clientes de alto valor

print("\nClientes con cluster asignado:")
print(
    datos_transformados[
        [
            "cliente_id",
            "ingreso_mensual",
            "frecuencia_compra",
            "gasto_promedio",
            "satisfaccion_codificada",
            "cluster"
        ]
    ].head()
)

# ============================================================
# 17. EVALUACIÓN DEL CLUSTERING
# ============================================================

# En esta etapa se evalúa la calidad de la segmentación
# realizada con el algoritmo K-Means.

# ------------------------------------------------------------
# Métrica utilizada: Silhouette Score
# ------------------------------------------------------------

# El coeficiente de Silhouette mide qué tan bien están separados
# los clusters y qué tan cohesionados son internamente.

# Su interpretación es la siguiente:
# - Cerca de 1  → clusters bien separados y bien definidos
# - Cerca de 0  → clusters superpuestos o poco diferenciados
# - Menor a 0  → mala asignación de clusters

# ------------------------------------------------------------
# Cálculo del Silhouette Score
# ------------------------------------------------------------

silhouette = silhouette_score(X_cluster_escalado, datos_transformados["cluster"])

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

print("\nCoeficiente Silhouette:")
print(round(silhouette, 3))

# ------------------------------------------------------------
# INTERPRETACIÓN
# ------------------------------------------------------------

# Un valor bajo de silhouette indica que los clusters no están
# claramente separados, lo que sugiere que:
# - Las variables pueden no ser suficientes para segmentar bien
# - O el valor de K (3 clusters) puede no ser el óptimo

# En este caso, el resultado debe interpretarse como una segmentación
# exploratoria más que como una división perfectamente definida.

# Esto significa que los clusters son útiles para análisis inicial,
# pero requieren validación adicional antes de usarse en decisiones críticas.

# ============================================================
# 18. PERFIL DE CADA CLUSTER
# ============================================================

# En esta etapa se analiza el comportamiento promedio de cada cluster
# generado por el algoritmo K-Means.

# ------------------------------------------------------------
# ¿Para qué sirve este análisis?
# ------------------------------------------------------------

# Permite interpretar qué representa cada grupo de clientes:
# - Si son clientes de alto o bajo valor
# - Si tienen mayor o menor frecuencia de compra
# - Cómo varía su nivel de satisfacción e ingreso

# ------------------------------------------------------------
# Cálculo del perfil promedio
# ------------------------------------------------------------

# Se agrupan los datos por cluster y se calcula la media
# de las variables utilizadas en la segmentación.

perfil_cluster = datos_transformados.groupby("cluster")[variables_cluster].mean()

# ------------------------------------------------------------
# RESULTADO
# ------------------------------------------------------------

print("\nPerfil promedio de cada cluster:")
print(perfil_cluster)

# ------------------------------------------------------------
# INTERPRETACIÓN
# ------------------------------------------------------------

# Cada fila representa un segmento de clientes:

# - Cluster con mayor ingreso y gasto promedio:
#   suele representar clientes de alto valor.

# - Cluster con menor frecuencia de compra:
#   puede representar clientes ocasionales o de bajo engagement.

# - Cluster con menor gasto pero posible alta satisfacción:
#   puede representar clientes potenciales o en desarrollo.

# Este análisis permite traducir los clusters en perfiles de negocio
# accionables para marketing, ventas y fidelización.

# En lugar de números abstractos, los clusters se convierten en
# "tipos de clientes" con características claras.

# ============================================================
# 19. VISUALIZACIÓN DE CLUSTERS
# ============================================================

# En esta etapa se visualizan los clusters generados por K-Means
# utilizando un gráfico de dispersión (scatter plot).

# ------------------------------------------------------------
# ¿Qué se está representando?
# ------------------------------------------------------------

# Eje X: frecuencia_compra
# → cuántas veces compra el cliente

# Eje Y: gasto_promedio
# → cuánto dinero gasta en promedio

# Color (hue): cluster
# → grupo asignado por el algoritmo K-Means

# ------------------------------------------------------------
# ¿Para qué sirve esta visualización?
# ------------------------------------------------------------

# Permite observar de forma intuitiva cómo se agrupan los clientes
# según su comportamiento de compra.

# Ayuda a identificar:
# - Clientes de alto valor (alta frecuencia y alto gasto)
# - Clientes ocasionales (baja frecuencia y bajo gasto)
# - Segmentos intermedios

# ------------------------------------------------------------
# INTERPRETACIÓN DE NEGOCIO
# ------------------------------------------------------------

# - Un cluster en la zona superior derecha suele representar
#   clientes más valiosos para la empresa.

# - Un cluster en la zona inferior izquierda suele representar
#   clientes de bajo engagement o compra ocasional.

# - Los clusters intermedios pueden representar oportunidades
#   de crecimiento mediante estrategias de marketing.

# ------------------------------------------------------------
# IMPORTANCIA
# ------------------------------------------------------------

# Esta visualización valida si la segmentación tiene sentido
# desde el punto de vista del negocio.

# Si los clusters se separan visualmente, el modelo tiene buena
# capacidad de segmentación.
# Si se superponen mucho, la separación entre grupos es débil
# y el modelo debe revisarse.

plt.figure(figsize=(8, 5))
sns.scatterplot(
data=datos_transformados,
x="frecuencia_compra",
y="gasto_promedio",
hue="cluster",
palette="Set2",
s=80
)
plt.title("Segmentación de clientes según frecuencia y gasto")
plt.xlabel("Frecuencia de compra")
plt.ylabel("Gasto promedio")
plt.show()

# ============================================================
# 20. INTERPRETACIÓN AUTOMÁTICA DE CLUSTERS
# ============================================================

# En esta etapa se traduce la salida del clustering en información
# útil para el negocio.

# ------------------------------------------------------------
# ¿Qué se está haciendo?
# ------------------------------------------------------------

# Se recorren todos los clusters generados por K-Means y se calculan
# sus valores promedio en variables clave:
# - ingreso_mensual
# - frecuencia_compra
# - gasto_promedio
# - satisfaccion_codificada

# ------------------------------------------------------------
# Objetivo
# ------------------------------------------------------------

# Convertir clusters numéricos (0, 1, 2) en perfiles de clientes
# entendibles para toma de decisiones empresariales.

# ------------------------------------------------------------
# Lógica de interpretación
# ------------------------------------------------------------

# Se utilizan medianas globales como punto de referencia:
# - Si gasto y frecuencia están por encima de la mediana:
#   → cliente de alto valor
#
# - Si ambos están por debajo:
#   → cliente ocasional o de bajo valor
#
# - Caso contrario:
#   → cliente de valor medio

# ------------------------------------------------------------
# RESULTADO POR CLUSTER
# ------------------------------------------------------------

print("\nINTERPRETACIÓN EMPRESARIAL DE LOS CLUSTERS")

for cluster in sorted(datos_transformados["cluster"].unique()):

    # Cálculo de promedios por cluster
    promedio_ingreso = perfil_cluster.loc[cluster, "ingreso_mensual"]
    promedio_frecuencia = perfil_cluster.loc[cluster, "frecuencia_compra"]
    promedio_gasto = perfil_cluster.loc[cluster, "gasto_promedio"]
    promedio_satisfaccion = perfil_cluster.loc[cluster, "satisfaccion_codificada"]

    # Mostrar métricas del cluster
    print("\nCluster", cluster)
    print("Ingreso promedio:", round(promedio_ingreso, 2))
    print("Frecuencia promedio:", round(promedio_frecuencia, 2))
    print("Gasto promedio:", round(promedio_gasto, 2))
    print("Satisfacción promedio:", round(promedio_satisfaccion, 2))

    # --------------------------------------------------------
    # REGLAS DE NEGOCIO
    # --------------------------------------------------------

    if (
        promedio_gasto >= perfil_cluster["gasto_promedio"].median()
        and promedio_frecuencia >= perfil_cluster["frecuencia_compra"].median()
    ):
        print("Interpretación: Clientes de alto valor comercial.")
        print(
            "Acción recomendada: ofrecer beneficios exclusivos, programa VIP y campañas de fidelización."
        )

    elif (
        promedio_gasto < perfil_cluster["gasto_promedio"].median()
        and promedio_frecuencia < perfil_cluster["frecuencia_compra"].median()
    ):
        print("Interpretación: Clientes ocasionales o de bajo consumo.")
        print(
            "Acción recomendada: enviar promociones de activación y descuentos personalizados."
        )

    else:
        print("Interpretación: Clientes de valor medio.")
        print(
            "Acción recomendada: aplicar campañas de venta cruzada y acumulación de puntos."
        )

# ------------------------------------------------------------
# CONCLUSIÓN
# ------------------------------------------------------------

# Este proceso convierte un resultado técnico (clusters numéricos)
# en segmentos de negocio accionables.

# Permite a la empresa:
# - Identificar clientes VIP
# - Detectar clientes inactivos o de bajo consumo
# - Diseñar estrategias de marketing diferenciadas

# En resumen, transforma análisis de datos en decisiones empresariales.

# ==========================================
# Respuestas directas a la actividad
# ==========================================

# 1. ¿Cuántos registros y cuántas variables tiene la base de datos inicial?
# La base tiene 150 registros y 8 variables.

# 2. ¿Qué errores o problemas fueron insertados en la base de datos?
# Se insertaron 4 valores faltantes, 1 outlier extremo en
# gasto_promedio = 15000 y 1 edad inconsistente con valor -5.

# 3. ¿Por qué fue necesario corregir la edad negativa?
# Porque una edad negativa no tiene sentido de negocio ni validez estadística.
# Si se deja, distorsiona el análisis y puede afectar al modelo.
# Por eso se reemplazó con la mediana de edades válidas (42).

# 4. ¿Por qué se reemplazaron los valores faltantes por la mediana o la moda?
# Porque la mediana es robusta ante valores extremos en variables numéricas
# y la moda conserva una categoría válida en variables cualitativas.
# Así se evita perder registros y se mantiene una imputación razonable.

# 5. ¿Por qué se normalizaron las variables antes de aplicar modelos?
# Porque ingreso, gasto y frecuencia tienen escalas distintas.
# Si no se escalan, una variable grande puede dominar el modelo o el clustering.
# Técnicamente, aquí se aplicó estandarización Z-score con StandardScaler.

# 6. ¿Cuál fue el valor de accuracy del modelo?
# El accuracy fue 0.500, es decir, el árbol acertó el 50 % de los casos
# del conjunto de prueba.

# 7. ¿Qué significa precision en este caso empresarial?
# Significa que, de todos los clientes que el modelo marcó como compra alta,
# solo 45.5 % realmente pertenecían a esa categoría.
# En negocio, esto mide cuántas campañas premium se enviarían
# a clientes correctos.

# 8. ¿Qué significa recall en este caso empresarial?
# Significa que el modelo logró detectar 58.8 % de los clientes
# que sí eran de compra alta.
# En negocio, muestra cuántas oportunidades valiosas se están capturando
# y cuántas se escapan.

# 9. ¿Cuál fue la variable más importante en el árbol de decisión?
# La variable más importante fue gasto_promedio,
# con una importancia de 0.4256.

# 10. ¿Cuántos clusters se generaron?
# Se generaron 3 clusters, pensados para representar clientes
# de bajo valor, valor medio y alto valor.

# ==========================================
# 3.2 Hallazgos clave
# ==========================================

# 1. La limpieza fue simple, pero obligatoria.
# Cuatro nulos, una edad inválida y un outlier bastaron para mostrar
# cómo un modelo puede deteriorarse si se entrena con errores.

# 2. El árbol no ofrece desempeño suficiente.
# Su accuracy de 0.500 está por debajo de un baseline ingenuo,
# por lo que no conviene usarlo como apoyo real para decisiones.

# 3. gasto_promedio sí concentra señal predictiva.
# Fue la variable más importante, seguida por frecuencia e ingreso.

# 4. Los clusters muestran valor comercial desigual.
# Hay un grupo ocasional, uno de alto potencial por ingreso
# y otro de valor alto con riesgo de satisfacción.

# 5. La segmentación es útil para explorar,
# no para cerrar decisiones sin validación adicional.
# El índice silhouette de 0.216 sugiere separación limitada.

# ==========================================
# 3.3 Recomendaciones
# ==========================================

# 1. No desplegar el árbol actual en producción.
# Antes debe mejorarse la variable objetivo
# o enriquecerse las variables predictoras.

# 2. Usar los clusters como base de campañas diferenciadas.
# No como verdad absoluta, sino como punto de partida comercial.

# 3. Fortalecer la calidad del dato desde el origen.
# Implementar validación de rangos, captura obligatoria
# y reglas automáticas para detectar valores extremos.